/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest5;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Clicknetcafe
 */
public class tugas1 extends javax.swing.JFrame {
    private DefaultTableModel model;
    /**
     * Creates new form TabelKegiatan
     */
    public tugas1() {
        initComponents();
    }
    
    public void InitTable() {
        model = new DefaultTableModel();
        model.addColumn("NAMA");
        model.addColumn("TELEPON");
        model.addColumn("KOTA ASAL");
        model.addColumn("JENIS KELAMIN");
        model.addColumn("TINGGI (CM)");
        model.addColumn("ALAMAT");
        tblpelanggan.setModel(model);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        grupgender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtnama = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnlaki = new javax.swing.JRadioButton();
        btncewe = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkota = new javax.swing.JComboBox<>();
        sltinggi = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        txttinggi = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpelanggan = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        Alamat = new javax.swing.JLabel();
        txtdanger = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnama.setText("jTextField1");
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 209, 28));

        txttelepon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttelepon.setText("jTextField1");
        jPanel1.add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 143, 28));

        jLabel1.setText("Nama");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("No. Telepon");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        grupgender.add(btnlaki);
        btnlaki.setText("Laki-Laki");
        btnlaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlakiActionPerformed(evt);
            }
        });
        jPanel1.add(btnlaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        grupgender.add(btncewe);
        btncewe.setText("Perempuan");
        jPanel1.add(btncewe, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane3.setViewportView(txtalamat);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 213, -1));

        jLabel4.setText("Jenis Kelamin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setText("Kota Asal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 105, -1, -1));

        txtkota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtkota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samarinda", "Balikpapan", "Bontang", "Penajam" }));
        jPanel1.add(txtkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 96, -1));

        sltinggi.setMaximum(190);
        sltinggi.setMinimum(140);
        sltinggi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sltinggiStateChanged(evt);
            }
        });
        jPanel1.add(sltinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 121, -1));

        jLabel5.setText("Tinggi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 34, -1));

        txttinggi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttinggi.setText("150");
        jPanel1.add(txttinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("cm");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        tblpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "TELEPON", "KOTA ASAL", "JENIS KELAMIN", "TINGGI", "ALAMAT"
            }
        ));
        tblpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpelanggan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 650, 100));

        btntambah.setBackground(new java.awt.Color(0, 204, 255));
        btntambah.setText("Tambah");
        btntambah.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btntambah.setBorderPainted(false);
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntambahMouseClicked(evt);
            }
        });
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, 40));

        btnsimpan.setBackground(new java.awt.Color(0, 204, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btnsimpan.setBorderPainted(false);
        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 90, 40));

        btnupdate.setBackground(new java.awt.Color(0, 204, 255));
        btnupdate.setText("Update");
        btnupdate.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btnupdate.setBorderPainted(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 90, 40));

        btnhapus.setBackground(new java.awt.Color(0, 204, 255));
        btnhapus.setText("Hapus");
        btnhapus.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btnhapus.setBorderPainted(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 90, 40));

        Alamat.setText("Alamat");
        jPanel1.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtdanger.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(txtdanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 430, 20));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 255));
        jLabel7.setText("TABEL PELANGGAN");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 27, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        InitTable();
    }//GEN-LAST:event_formComponentShown

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        txtnama.setEnabled(true);
        txttelepon.setEnabled(true);
        txtkota.setEnabled(true);
        btnlaki.setEnabled(true);
        btncewe.setEnabled(true);
        sltinggi.setEnabled(true);
        sltinggi.setValue(160);
        jLabel8.setEnabled(true);
        txtalamat.setEnabled(true);
        txttinggi.setEnabled(true); 
        txtdanger.setText("");
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            model.removeRow(tblpelanggan.getSelectedRow());
            
        }
        catch(ArrayIndexOutOfBoundsException e) {
            txtdanger.setText("Tidak ada record terpilih !!!");
        }
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        txtnama.setEnabled(false);
        txttelepon.setEnabled(false);
        txtkota.setEnabled(false);
        btnlaki.setEnabled(false);
        btncewe.setEnabled(false);
        sltinggi.setEnabled(false);
        jLabel8.setEnabled(false);
        txtalamat.setEnabled(false);
        txttinggi.setEnabled(false);
        btnlaki.setSelected(true);
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

    if(!txtnama.getText().trim().equals("") && !txttelepon.getText().trim().equals("") && !txtalamat.getText().trim().equals("")) {
        Object[] data = new Object[6];
        data[0] = txtnama.getText();
        data[1] = txttelepon.getText();
        data[2] = txtkota.getSelectedItem().toString();
        if (btnlaki.isSelected()) {
            data[3] = btnlaki.getText();
        }
        else if (btncewe.isSelected()) {
            data[3] = btncewe.getText();
        }
        data[4] = sltinggi.getValue();
        data[5] = txtalamat.getText();
               
        model.addRow(data);
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        txtnama.setEnabled(false);
        txttelepon.setEnabled(false);
        txtkota.setEnabled(false);
        btnlaki.setEnabled(false);
        btncewe.setEnabled(false);
        sltinggi.setEnabled(false);
        jLabel8.setEnabled(false);
        txtalamat.setEnabled(false);
        txttinggi.setEnabled(false);
        btnlaki.setSelected(true);
    }
    else {
	txtdanger.setText("*isian tidak boleh ada yang kosong");
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        txtnama.setEnabled(false);
        txttelepon.setEnabled(false);
        txtkota.setEnabled(false);
        btnlaki.setEnabled(false);
        btncewe.setEnabled(false);
        sltinggi.setEnabled(false);
        jLabel8.setEnabled(false);
        txtalamat.setEnabled(false);
        txttinggi.setEnabled(false);
        btnlaki.setSelected(true);
    }
        
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnlakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlakiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtnama.setText("");
        txttelepon.setText("");
        txtalamat.setText("");
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        txtnama.setEnabled(false);
        txttelepon.setEnabled(false);
        txtkota.setEnabled(false);
        btnlaki.setEnabled(false);
        btncewe.setEnabled(false);
        sltinggi.setEnabled(false);
        jLabel8.setEnabled(false);
        txtalamat.setEnabled(false);
        txttinggi.setEnabled(false);
        btnlaki.setSelected(true); 
    }//GEN-LAST:event_formWindowOpened

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {          
//            if(!txtnama.getText().trim().equals("") && !txttelepon.getText().trim().equals("") && !txtalamat.getText().trim().equals("")) {
                DefaultTableModel model = (DefaultTableModel) tblpelanggan.getModel();
                model.setValueAt(txtnama.getText(), tblpelanggan.getSelectedRow(), 0);
                model.setValueAt(txttelepon.getText(), tblpelanggan.getSelectedRow(), 1);
                model.setValueAt(txtkota.getSelectedItem().toString(), tblpelanggan.getSelectedRow(), 2);
                if(btnlaki.isSelected()) {
                    model.setValueAt(btnlaki.getText(), tblpelanggan.getSelectedRow(), 3);
                }
                else if(btncewe.isSelected()) {
                    model.setValueAt(btncewe.getText(), tblpelanggan.getSelectedRow(), 3);
                }
                model.setValueAt(sltinggi.getValue(), tblpelanggan.getSelectedRow(), 4);
                model.setValueAt(txtalamat.getText(), tblpelanggan.getSelectedRow(), 5);
                txtdanger.setText("Record Berhasil di Update");
//            }
//            else {
//                txtdanger.setText("*isian tidak boleh ada yang kosong");
//                btntambah.setEnabled(true);
//                btnsimpan.setEnabled(false);
//                btnupdate.setEnabled(false);
//                btnhapus.setEnabled(false);
//                txtnama.setEnabled(false);
//                txttelepon.setEnabled(false);
//                txtkota.setEnabled(false);
//                btnlaki.setEnabled(false);
//                btncewe.setEnabled(false);
//                sltinggi.setEnabled(false);
//                jLabel8.setEnabled(false);
//                txtalamat.setEnabled(false);
//                txttinggi.setEnabled(false);
//                btnlaki.setSelected(true);
//            } 
        }
        catch (ArrayIndexOutOfBoundsException e) {
            txtdanger.setText("Pastikan ada record terpilih dan lengkapi form isian");
        }
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        txtnama.setEnabled(false);
        txttelepon.setEnabled(false);
        txtkota.setEnabled(false);
        btnlaki.setEnabled(false);
        btncewe.setEnabled(false);
        sltinggi.setEnabled(false);
        jLabel8.setEnabled(false);
        txtalamat.setEnabled(false);
        txttinggi.setEnabled(false);
        btnlaki.setSelected(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btntambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseClicked

        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(true);
        btnhapus.setEnabled(true);
        
    }//GEN-LAST:event_btntambahMouseClicked

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void sltinggiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sltinggiStateChanged
        txttinggi.setText(String.valueOf(sltinggi.getValue()));
    }//GEN-LAST:event_sltinggiStateChanged

    private void tblpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpelangganMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblpelanggan.getModel();
        txtnama.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 0).toString());
        txttelepon.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 1).toString());
        txtkota.setSelectedItem(model.getValueAt(tblpelanggan.getSelectedRow(), 2).toString());
        if(btnlaki.isSelected()) {
            btnlaki.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 3).toString());
        }
        else {
            btncewe.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 3).toString());
        }
        sltinggi.setValue((int) model.getValueAt(tblpelanggan.getSelectedRow(), 4));
        txtnama.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tblpelangganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JRadioButton btncewe;
    private javax.swing.JButton btnhapus;
    private javax.swing.JRadioButton btnlaki;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup grupgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JSlider sltinggi;
    private javax.swing.JTable tblpelanggan;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JLabel txtdanger;
    private javax.swing.JComboBox<String> txtkota;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JLabel txttinggi;
    // End of variables declaration//GEN-END:variables
}
