/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest5;

import Posttest5.tugas1;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Clicknetcafe
 */
public class tugas1_1 extends javax.swing.JFrame {
    private DefaultTableModel model1;
    /**
     * Creates new form TabelKegiatan
     */
    public tugas1_1() {
        initComponents();
    }
    
    public void InitTable() {
        model1 = new DefaultTableModel();
        model1.addColumn("NAMA");
        model1.addColumn("TELEPON");
        model1.addColumn("KOTA ASAL");
        model1.addColumn("JENIS KELAMIN");
        model1.addColumn("STATUS");
        model1.addColumn("ALAMAT");
        tblpelanggan.setModel(model1);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        grupgender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        telepon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kota = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpelanggan = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        Alamat = new javax.swing.JLabel();
        txtdanger = new javax.swing.JLabel();
        ckaktif = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nama.setText("jTextField1");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 209, 28));

        telepon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telepon.setText("jTextField1");
        jPanel1.add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 143, 28));

        jLabel1.setText("Nama");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("No. Telepon");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        grupgender.add(laki);
        laki.setText("Laki-Laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel1.add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        grupgender.add(perempuan);
        perempuan.setText("Perempuan");
        jPanel1.add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane3.setViewportView(alamat);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 213, -1));

        jLabel4.setText("Jenis Kelamin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setText("Kota Asal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 105, -1, -1));

        kota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samarinda", "Balikpapan", "Bontang", "Penajam" }));
        jPanel1.add(kota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 96, -1));

        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 34, -1));

        tblpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "TELEPON", "KOTA ASAL", "JENIS KELAMIN", "STATUS", "ALAMAT"
            }
        ));
        tblpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpelanggan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 650, 100));

        btntambah.setBackground(new java.awt.Color(0, 204, 255));
        btntambah.setText("Tambah");
        btntambah.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btntambah.setBorderPainted(false);
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntambahMouseClicked(evt);
            }
        });
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, 40));

        btnsimpan.setBackground(new java.awt.Color(0, 204, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btnsimpan.setBorderPainted(false);
        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 90, 40));

        btnupdate.setBackground(new java.awt.Color(0, 204, 255));
        btnupdate.setText("Update");
        btnupdate.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btnupdate.setBorderPainted(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 90, 40));

        btnhapus.setBackground(new java.awt.Color(0, 204, 255));
        btnhapus.setText("Hapus");
        btnhapus.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(153, 255, 0)));
        btnhapus.setBorderPainted(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 90, 40));

        Alamat.setText("Alamat");
        jPanel1.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtdanger.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(txtdanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 430, 20));

        ckaktif.setText("Aktif");
        ckaktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckaktifActionPerformed(evt);
            }
        });
        jPanel1.add(ckaktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 255));
        jLabel7.setText("TABEL PELANGGAN");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 27, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        InitTable();
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        nama.setText("");
        telepon.setText("");
        alamat.setText("");
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        nama.setEnabled(false);
        telepon.setEnabled(false);
        kota.setEnabled(false);
        laki.setEnabled(false);
        perempuan.setEnabled(false);
        alamat.setEnabled(false);
        laki.setSelected(true); 
    }//GEN-LAST:event_formWindowOpened

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            model1.removeRow(tblpelanggan.getSelectedRow());

        }
        catch(ArrayIndexOutOfBoundsException e) {
            txtdanger.setText("Tidak ada record terpilih !!!");
        }
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        nama.setEnabled(false);
        telepon.setEnabled(false);
        kota.setEnabled(false);
        laki.setEnabled(false);
        perempuan.setEnabled(false);
        alamat.setEnabled(false);
        laki.setSelected(true);

    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            //            if(!txtnama.getText().trim().equals("") && !txttelepon.getText().trim().equals("") && !txtalamat.getText().trim().equals("")) {
                DefaultTableModel model = (DefaultTableModel) tblpelanggan.getModel();
                model.setValueAt(nama.getText(), tblpelanggan.getSelectedRow(), 0);
                model.setValueAt(telepon.getText(), tblpelanggan.getSelectedRow(), 1);
                model.setValueAt(kota.getSelectedItem().toString(), tblpelanggan.getSelectedRow(), 2);
                if(laki.isSelected()) {
                    model.setValueAt(laki.getText(), tblpelanggan.getSelectedRow(), 3);
                }
                else if(perempuan.isSelected()) {
                    model.setValueAt(perempuan.getText(), tblpelanggan.getSelectedRow(), 3);
                }
                if(ckaktif.isSelected()) {
                    model.setValueAt(ckaktif.getText(), tblpelanggan.getSelectedRow(), 4);
                }
                else if(ckaktif.isSelected()) {
                    model.setValueAt(ckaktif.getText(), tblpelanggan.getSelectedRow(), 4);
                }
                model.setValueAt(alamat.getText(), tblpelanggan.getSelectedRow(), 5);
                txtdanger.setText("Record Berhasil di Update");
        }
        catch (ArrayIndexOutOfBoundsException e) {
            txtdanger.setText("Pastikan ada record terpilih dan lengkapi form isian");
        }
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        nama.setEnabled(false);
        telepon.setEnabled(false);
        kota.setEnabled(false);
        laki.setEnabled(false);
        perempuan.setEnabled(false);
        alamat.setEnabled(false);
        laki.setSelected(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

        if(!nama.getText().trim().equals("") && !telepon.getText().trim().equals("") && !alamat.getText().trim().equals("")) {
            Object[] data = new Object[6];
            data[0] = nama.getText();
            data[1] = telepon.getText();
            data[2] = kota.getSelectedItem().toString();
            if (laki.isSelected()) {
                data[3] = laki.getText();
            }
            else if (perempuan.isSelected()) {
                data[3] = perempuan.getText();
            }
            if (ckaktif.isSelected()) {
                data[4] = ckaktif.getText();
            }
            else if (ckaktif.isSelected()) {
                data[4] = ckaktif.getText();
            }
            data[5] = alamat.getText();

            model1.addRow(data);
            btntambah.setEnabled(true);
            btnsimpan.setEnabled(false);
            btnupdate.setEnabled(false);
            btnhapus.setEnabled(false);
            nama.setEnabled(false);
            telepon.setEnabled(false);
            kota.setEnabled(false);
            laki.setEnabled(false);
            perempuan.setEnabled(false);
            alamat.setEnabled(false);
            laki.setSelected(true);
        }
        else {
            txtdanger.setText("*isian tidak boleh ada yang kosong");
            btntambah.setEnabled(true);
            btnsimpan.setEnabled(false);
            btnupdate.setEnabled(false);
            btnhapus.setEnabled(false);
            nama.setEnabled(false);
            telepon.setEnabled(false);
            kota.setEnabled(false);
            laki.setEnabled(false);
            perempuan.setEnabled(false);
            alamat.setEnabled(false);
            laki.setSelected(true);
        }

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        nama.setEnabled(true);
        telepon.setEnabled(true);
        kota.setEnabled(true);
        laki.setEnabled(true);
        perempuan.setEnabled(true);
        alamat.setEnabled(true);
        txtdanger.setText("");
    }//GEN-LAST:event_btntambahActionPerformed

    private void btntambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseClicked

        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(true);
        btnhapus.setEnabled(true);

    }//GEN-LAST:event_btntambahMouseClicked

    private void tblpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpelangganMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblpelanggan.getModel();
        nama.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 0).toString());
        telepon.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 1).toString());
        kota.setSelectedItem(model.getValueAt(tblpelanggan.getSelectedRow(), 2).toString());
        if(laki.isSelected()) {
            laki.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 3).toString());
        }
        else {
            perempuan.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 3).toString());
        }
        if(ckaktif.isSelected()) {
            ckaktif.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 4).toString());
        }
        else {
            ckaktif.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 4).toString());
        }
        nama.setText(model.getValueAt(tblpelanggan.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tblpelangganMouseClicked

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void ckaktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckaktifActionPerformed
        if(ckaktif.isSelected()) {
            ckaktif.setText("Aktif");
        }
        else if(!ckaktif.isSelected()) {
            ckaktif.setText("Tidak Aktif");
        }
    }//GEN-LAST:event_ckaktifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas1_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JCheckBox ckaktif;
    private javax.swing.ButtonGroup grupgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> kota;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTable tblpelanggan;
    private javax.swing.JTextField telepon;
    private javax.swing.JLabel txtdanger;
    // End of variables declaration//GEN-END:variables
}
